const spellBooks = {
  standard: {
    combat: [
      { name: 'Wind Strike', level: 1, runes: { air: 1, mind: 1 } },
      { name: 'Confuse', level: 3, runes: { earth: 2, water: 3, body: 1 } },
      { name: 'Water Strike', level: 5, runes: { air: 1, water: 1, mind: 1 } },
      { name: 'Earth Strike', level: 9, runes: { air: 1, earth: 2, mind: 1 } },
      { name: 'Weaken', level: 11, runes: { earth: 2, water: 3, body: 1 } },
      { name: 'Fire Strike', level: 13, runes: { air: 2, fire: 3, mind: 1 } },
      { name: 'Wind Bolt', level: 17, runes: { air: 2, chaos: 1 } },
      { name: 'Curse', level: 19, runes: { earth: 3, water: 2, body: 1 } },
      { name: 'Bind', level: 20, runes: { earth: 3, water: 3, nature: 2 } },
      { name: 'Water Bolt', level: 23, runes: { air: 2, water: 2, chaos: 1 } },
      { name: 'Earth Bolt', level: 29, runes: { air: 2, earth: 3, chaos: 1 } },
      { name: 'Fire Bolt', level: 35, runes: { air: 3, fire: 4, chaos: 1 } },
      { name: 'Crumble Undead', level: 39, runes: { air: 2, earth: 2, chaos: 1 } },
      { name: 'Wind Blast', level: 41, runes: { air: 3, death: 1 } },
      { name: 'Water Blast', level: 47, runes: { air: 3, water: 3, death: 1 } },
      { name: 'Iban Blast', level: 50, runes: { fire: 5, death: 1 } },
      { name: 'Snare', level: 50, runes: { earth: 4, water: 4, nature: 3 } },
      { name: 'Magic Dart', level: 50, runes: { death: 1, mind: 4 } },
      { name: 'Earth Blast', level: 53, runes: { air: 3, earth: 4, death: 1 } },
      { name: 'Fire Blast', level: 59, runes: { air: 4, fire: 5, death: 1 } },
      { name: 'Saradomin Strike', level: 60, runes: { air: 4, fire: 2, blood: 2 } },
      { name: 'Flames of Zamorak', level: 60, runes: { air: 1, fire: 4, blood: 2 } },
      { name: 'Claws of Guthix', level: 60, runes: { air: 4, fire: 1, blood: 2 } },
      { name: 'Wind Wave', level: 62, runes: { air: 5, blood: 1 } },
      { name: 'Water Wave', level: 65, runes: { air: 5, water: 7, blood: 1 } },
      { name: 'Vulnerability', level: 66, runes: { earth: 5, water: 5, soul: 1 } },
      { name: 'Earth Wave', level: 70, runes: { air: 5, earth: 7, blood: 1 } },
      { name: 'Enfeeble', level: 73, runes: { earth: 8, water: 8, soul: 1 } },
      { name: 'Fire Wave', level: 75, runes: { air: 5, fire: 7, blood: 1 } },
      { name: 'Entangle', level: 79, runes: { earth: 5, water: 5, nature: 4 } },
      { name: 'Stun', level: 80, runes: { earth: 12, water: 12, soul: 1 } },
      { name: 'Charge', level: 80, runes: { air: 3, fire: 3, blood: 3 } },
      { name: 'Wind Surge', level: 81, runes: { air: 7, wrath: 1 } },
      { name: 'Water Surge', level: 85, runes: { air: 7, water: 10, wrath: 1 } },
      { name: 'Tele Block', level: 85, runes: { chaos: 1, death: 1, law: 1 } },
      { name: 'Teleport to Target', level: 85, runes: { chaos: 1, death: 1, law: 1 } },
      { name: 'Lvl-7 Enchant', level: 93, runes: { blood: 20, cosmic: 1, soul: 20 } },
      { name: 'Fire Surge', level: 95, runes: { air: 7, fire: 10, wrath: 1 } }
    ],
    utility: [
      { name: 'Lumbridge Home Teleport', level: 0, runes: {} },
      { name: 'Enchant Crossbow Bolt (Opal)', level: 4, runes: { air: 2, cosmic: 1 } },
      { name: 'Lvl-1 Enchant', level: 7, runes: { water: 1, cosmic: 1 } },
      { name: 'Enchant Crossbow Bolt (Sapphire)', level: 7, runes: { water: 1, cosmic: 1, mind: 1 } },
      { name: 'Bones to Bananas', level: 15, runes: { earth: 2, water: 2, nature: 1 } },
      { name: 'Low Level Alchemy', level: 21, runes: { fire: 3, nature: 1 } },
      { name: 'Enchant Crossbow Bolt (Pearl)', level: 24, runes: { water: 2, cosmic: 1 } },
      { name: 'Varrock Teleport', level: 25, runes: { air: 3, fire: 1, law: 1 } },
      { name: 'Lvl-2 Enchant', level: 27, runes: { air: 3, cosmic: 1 } },
      { name: 'Enchant Crossbow Bolt (Emerald)', level: 27, runes: { air: 3, cosmic: 1, nature: 1 } },
      { name: 'Enchant Crossbow Bolt (Red Topaz)', level: 29, runes: { fire: 2, cosmic: 1 } },
      { name: 'Lumbridge Teleport', level: 31, runes: { air: 3, earth: 1, law: 1 } },
      { name: 'Telekinetic Grab', level: 33, runes: { air: 1, law: 1 } },
      { name: 'Falador Teleport', level: 37, runes: { air: 3, water: 1, law: 1 } },
      { name: 'Teleport to House', level: 40, runes: { earth: 1, law: 1, air: 1 } },
      { name: 'Superheat Item', level: 43, runes: { fire: 4, nature: 1 } },
      { name: 'Camelot Teleport', level: 45, runes: { air: 5, law: 1 } },
      { name: 'Kourend Castle Teleport', level: 48, runes: { water: 1, fire: 1, law: 2 } },
      { name: 'Lvl-3 Enchant', level: 49, runes: { fire: 5, cosmic: 1 } },
      { name: 'Enchant Crossbow Bolt (Ruby)', level: 49, runes: { fire: 5, cosmic: 1, blood: 1 } },
      { name: 'Ardougne Teleport', level: 51, runes: { water: 2, law: 2 } },
      { name: 'High Level Alchemy', level: 55, runes: { fire: 5, nature: 1 } },
      { name: 'Charge Water Orb', level: 56, runes: { water: 30, cosmic: 3 } },
      { name: 'Lvl-4 Enchant', level: 57, runes: { earth: 10, cosmic: 1 } },
      { name: 'Enchant Crossbow Bolt (Diamond)', level: 57, runes: { earth: 10, cosmic: 1, law: 2 } },
      { name: 'Watchtower Teleport', level: 58, runes: { earth: 2, law: 2 } },
      { name: 'Charge Earth Orb', level: 60, runes: { earth: 30, cosmic: 3 } },
      { name: 'Bones to Peaches', level: 60, runes: { earth: 2, water: 4, nature: 2 } },
      { name: 'Trollheim Teleport', level: 61, runes: { fire: 2, law: 2 } },
      { name: 'Charge Fire Orb', level: 63, runes: { fire: 30, cosmic: 3 } },
      { name: 'Ape Atoll Teleport', level: 64, runes: { fire: 2, water: 2, law: 2, banana: 1 } },
      { name: 'Charge Air Orb', level: 66, runes: { air: 30, cosmic: 3 } },
      { name: 'Lvl-5 Enchant', level: 68, runes: { earth: 15, water: 15, cosmic: 1 } },
      { name: 'Enchant Crossbow Bolt (Dragonstone)', level: 68, runes: { earth: 15, cosmic: 1, soul: 1 } },
      { name: 'Teleother Lumbridge', level: 74, runes: { earth: 1, law: 1, soul: 1 } },
      { name: 'Teleother Falador', level: 82, runes: { water: 1, law: 1, soul: 1 } },
      { name: 'Teleport to Target', level: 85, runes: { chaos: 1, death: 1, law: 1 } },
      { name: 'Lvl-6 Enchant', level: 87, runes: { earth: 20, fire: 20, cosmic: 1 } },
      { name: 'Enchant Crossbow Bolt (Onyx)', level: 87, runes: { fire: 20, cosmic: 1, death: 1 } },
      { name: 'Teleother Camelot', level: 90, runes: { law: 1, soul: 2 } }
    ]
  },
  ancients: {
    combat: [
      { name: 'Smoke Rush', level: 50, runes: { air: 1, fire: 1, chaos: 2, death: 2 } },
      { name: 'Shadow Rush', level: 52, runes: { air: 1, chaos: 2, death: 2, soul: 1 } },
      { name: 'Blood Rush', level: 56, runes: { blood: 1, chaos: 2, death: 2 } },
      { name: 'Ice Rush', level: 58, runes: { water: 2, chaos: 2, death: 2 } },
      { name: 'Smoke Burst', level: 62, runes: { air: 2, fire: 2, chaos: 4, death: 2 } },
      { name: 'Shadow Burst', level: 64, runes: { air: 1, chaos: 4, death: 2, soul: 2 } },
      { name: 'Blood Burst', level: 68, runes: { blood: 2, chaos: 4, death: 2 } },
      { name: 'Ice Burst', level: 70, runes: { water: 4, chaos: 4, death: 2 } },
      { name: 'Smoke Blitz', level: 74, runes: { air: 2, fire: 2, blood: 2, death: 2 } },
      { name: 'Shadow Blitz', level: 76, runes: { air: 2, blood: 2, death: 2, soul: 2 } },
      { name: 'Blood Blitz', level: 80, runes: { blood: 4, death: 2 } },
      { name: 'Ice Blitz', level: 82, runes: { water: 3, blood: 2, death: 2 } },
      { name: 'Smoke Barrage', level: 86, runes: { air: 4, fire: 4, blood: 2, death: 4 } },
      { name: 'Shadow Barrage', level: 88, runes: { air: 4, blood: 2, death: 4, soul: 3 } },
      { name: 'Blood Barrage', level: 92, runes: { blood: 4, death: 4, soul: 1 } },
      { name: 'Ice Barrage', level: 94, runes: { water: 6, blood: 2, death: 4 } }
    ],
    utility: [
      { name: 'Edgeville Home Teleport', level: 0, runes: {} },
      { name: 'Paddewwa Teleport', level: 54, runes: { air: 1, fire: 1, law: 2 } },
      { name: 'Senntisten Teleport', level: 60, runes: { law: 2, soul: 1, death: 1 } },
      { name: 'Kharyrll Teleport', level: 66, runes: { law: 2, water: 1, air: 1 } },
      { name: 'Lassar Teleport', level: 72, runes: { law: 2, fire: 1, water: 2 } },
      { name: 'Dareeyak Teleport', level: 78, runes: { law: 2, fire: 2, air: 2 } },
      { name: 'Carrallanger Teleport', level: 84, runes: { law: 2, soul: 2, chaos: 2 } },
      { name: 'Teleport to Target', level: 85, runes: { chaos: 1, death: 1, law: 1 } },
      { name: 'Annakarl Teleport', level: 90, runes: { law: 2, blood: 2 } },
      { name: 'Ghorrock Teleport', level: 96, runes: { law: 2, water: 8 } }
    ]
  }
};

export default spellBooks;
